### ISSUE TITLE
Registrar Error; Error connecting to tls://epp.centralnic.com:700: (code 0)

### ISSUE THREAD

**Issue by mkmonir123** [centralnic/php-epp#13]
Hello,
I have added my server's IPs at CentralNIC registers console's access list. But still getting error "Registrar Error, Error connecting to tls://epp.centralnic.com:700: (code 0)"
I have tasted the module with WHMCS v7.x, 6.x and 5.3.x. But getting same error. Please tell me how to solve it. Thanks
-Best Regards
Mostafa Kamal
![capture](https://user-images.githubusercontent.com/10987571/34300656-391fd6e8-e753-11e7-910b-b75be5d7e979.PNG)

**Comment by jodrell** [comment]
Please re-submit to support@centralnic.com.
